# Site settings
title: Lacey-Anne Sanderson
twitter_username: laceysanderson
github_username: laceysanderson
name: Lacey-Anne Sanderson

position: Bioinformatics Research Assistant, Pulse Crop Research
employer: University of Saskatchewan, Plant Sciences

intro: Formally trained in botony and molecular biology with a sprinkling of computer science and practically trained in web development and plant breeding, I often feel like I'm straddling two worlds and belong in neither of them, which is just to say, I am a Bioinformaticist ;-). People either know me as the lead developer of KnowPulse or one of the core developers of Tripal --luckily they are both an end to the same mean.

# Build settings
markdown: kramdown

# User specific content
# Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/laceysanderson
 - title: Drupal.org
   url: https://www.drupal.org/u/laceysanderson
 - title: Twitter
   url: https://twitter.com/laceysanderson
 - title: KnowPulse
   url: http://knowpulse.usask.ca/portal
 - title: UofS Pulse Binfo
   url: https://github.com/UofS-Pulse-Binfo
 - title: Tripal
   url: https://github.com/tripal

# Any buzzword skills you want to include
skills:
 - PortgreSQL
 - Drupal
 - PHP
 - Javascript
 - Tripal

# Work experience is required
roles:
 - title: Bioinformatics Research Assistant
   start: January 2012
   end: Ongoing
   employer: Pulse Crop Research, Plant Sciences, University of Saskatchewan
   description: 
 - title: Bioinformatics Research Technician
   start: May 2009
   end: January 2012
   employer: Pulse Crop Research, Plant Sciences, University of Saskatchewan
   description: Design of programs to aid in research and implementation of a database web portal for organization, storage and utilization of sequence and germplasm data.
 - title: Teaching Assistant
   start: January 2009
   end: April 2009
   employer: Biology Department, University of Saskatchewan
   description: BIOL 202 Introductory Botany
 - title: Summer Research Student
   start: May 2008
   end: September 2008 
   employer: Bonham-Smith Lab, University of Saskatchewan
   description: Design and management of an individual project on the ribosomal protein S15aC
 - title: Teaching Assistant
   start: January 2008
   end: April 2008
   employer: Biology Department, University of Saskatchewan
   description: BIOL 331 Plant Physiology
 - title: Summer Research Student
   start: May 2007
   end: September 2007
   employer: Wilson Lab, University of Saskatchewan
   description: Assisting lab graduate students with molecular biology techniques


# Education is required
education:
 - level: Bachelor of Science (B.Sc.) Honours
   date: 2009
   subject: "Major: Biology, Specialized in Molecular Biology & Botany"
   school: University of Saskatchewan
 - level: Honours Certificate in Science (B.Sc. equivalent)
   date: 2009
   subject: "Major: Bioinformatics"
   school: University of Saskatchewan

# List of interesting Github repo/projects to include - optional
github:
 - tripal/tripal
 - tripal/tripal_blast
 - UofS-Pulse-Binfo/nd_genotypes 
 - tripal/trpdownload_api 
 - tripal/tripald3
 - tripal/trpfancy_fields

# An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
#   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I #have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in #addition to others.  In my current role Groovy is the primary language used - and I am #familiar with many of the languages features and quirks (including writing <a #target='_blank' #href="https://dzone.com/articles/functional-programming-groovy">Functional Programming #style groovy</a>). <br/><br/>