# Site settings
title: Lacey-Anne Sanderson
twitter_username: laceysanderson
github_username: laceysanderson
name: Lacey-Anne Sanderson

position: Bioinformatics Research Assistant, Pulse Crop Research
employer: University of Saskatchewan, Plant Sciences

intro: Formally trained in <em class="pop small">botony and molecular biology</em> with a sprinkling of <em class="pop small">computer science</em> and practically trained in <em class="pop small">web development</em> and <em class="pop small">plant breeding</em>, I often feel like I'm straddling two worlds and belong in neither of them, which is just to say, <em class="pop big">I am a Bioinformaticist</em> ;-). People either know me as the <em class="pop med">lead developer of KnowPulse</em> or <em class="pop med">one of the core developers of Tripal</em> --luckily they are both an end to the same mean.

# Build settings
markdown: kramdown

# User specific content
# Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/laceysanderson
 - title: Drupal.org
   url: https://www.drupal.org/u/laceysanderson
 - title: Twitter
   url: https://twitter.com/laceysanderson
 - title: KnowPulse
   url: http://knowpulse.usask.ca/portal
 - title: UofS Pulse Binfo
   url: https://github.com/UofS-Pulse-Binfo
 - title: Tripal
   url: https://github.com/tripal

# Any buzzword skills you want to include
skills:
 - PortgreSQL
 - Drupal
 - PHP
 - Javascript
 - Tripal

# List of interesting Github repo/projects to include - optional
github:
 - tripal/tripal
 - tripal/tripal_blast
 - UofS-Pulse-Binfo/nd_genotypes 
 - tripal/trpdownload_api 
 - tripal/tripald3
 - tripal/trpfancy_fields

# Education is required
education:
 - level: Bachelor of Science (B.Sc.) Honours
   date: 2009
   subject: "Major: Biology, Specialized in Molecular Biology & Botany"
   school: University of Saskatchewan
 - level: Honours Certificate in Science (B.Sc. equivalent)
   date: 2009
   subject: "Major: Bioinformatics"
   school: University of Saskatchewan

# Work experience is required
roles:
 - title: Bioinformatics Research Assistant
   start: January 2012
   end: Ongoing
   employer: Pulse Crop Research, Plant Sciences, University of Saskatchewan
   description: 'Lead developement and maitenance of <a href="http://knowpulse.usask.ca">KnowPulse</a>, a breeder-friendly pulse crop web portal and participate in development of Tripal, the software powering KnowPulse. Provide bioinformatics support and advice to the members of Pulse Group, and perform community outreach for Tripal including presenting at conferences, leading workshops and consulting with other projects on Tripal functionality/integration.'
 - title: Bioinformatics Research Technician
   start: May 2009
   end: January 2012
   employer: Pulse Crop Research, Plant Sciences, University of Saskatchewan
   description: Design of programs to aid in research and implementation of a database web portal for organization, storage and utilization of sequence and germplasm data.
 - title: Teaching Assistant
   start: January 2009
   end: April 2009
   employer: Biology Department, University of Saskatchewan
   description: BIOL 202 Introductory Botany
 - title: Summer Research Student
   start: May 2008
   end: September 2008 
   employer: Bonham-Smith Lab, University of Saskatchewan
   description: Design and management of an individual project on the ribosomal protein S15aC
 - title: Teaching Assistant
   start: January 2008
   end: April 2008
   employer: Biology Department, University of Saskatchewan
   description: BIOL 331 Plant Physiology
 - title: Summer Research Student
   start: May 2007
   end: September 2007
   employer: Wilson Lab, University of Saskatchewan
   description: Assisting lab graduate students with molecular biology techniques

presentations:
 - title: "Tripal Database Network and Initiatives"
   role: Workshop Organizer
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2017
   url: https://pag.confex.com/pag/xxv/webprogram/Session4309.html
 - title: "Tripal User Meeting & Hackathon"
   role: Organizer
   venue: Tripal Developer Community Meeting
   date: Jan 2017
   url: https://tripal.info/node/328
 - title: "Extending Tripal for Community-Based Management and Distribution of Genotypic and Phenotypic Data"
   role: Oral Presentatio 
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2017
   url: https://pag.confex.com/pag/xxv/webprogram/Paper25949.html
 - title: "Tripal Database Network and Initiatives"
   role: Workshop Organizer
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2016
   url: https://pag.confex.com/pag/xxiv/webprogram/Session3182.html
 - title: "Tripal Codefest"
   role: Organizer
   venue: Tripal Developer Community Meeting
   date: Jan 2016
   url: https://docs.google.com/document/d/1dOGErGe8UNcWD-6sHWhpCJqgAVgukZhb-MR3cBEokss/edit
 - title: "Tripal v2: An Overview"
   role: Oral Presentation
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2016
   url: https://pag.confex.com/pag/xxiv/webprogram/Paper20561.html 
 - title: "Tripal (Community Update)"
   role: Oral Presentation
   venue: GMOD Conference
   date: Jun 2016
   url: http://gmod.org/wiki/Jun_2016_GMOD_Meeting 
 - title: "Extending Tripal for Specialized Display and Management of Diversity and Breeding Data"
   role: Oral Presentation
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2015
   url: https://pag.confex.com/pag/xxiii/webprogram/Paper14948.html 
 - title: "KnowPulse: A Breeder-Focused Web Portal That Integrates Genetics and Genomics of Pulse Crops with Model Genomes"
   role: Oral Presentation
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2015
   url: https://pag.confex.com/pag/xxiii/webprogram/Paper17190.html 
 - title: "Tripal (Community Update)"
   role: Oral Presentation
   venue: Plant and Animal Genome (PAG) Conference
   date: Jan 2014
   url: https://pag.confex.com/pag/xxii/webprogram/Paper10624.html 
 - title: "Tripal (Community Update)"
   role: Oral Presentation
   venue: GMOD Conference
   date: Jan 2014
   url: http://gmod.org/wiki/Jan_2014_GMOD_Meeting 
 - title: "Tripal (Community Update)"
   role: Oral Presentation
   venue: GMOD Conference
   date: Jan 2012
   url: http://gmod.org/wiki/April_2012_GMOD_Meeting

# Publications
publications:
 - title: "AgBioData consortium recommendations for sustainable genomics and genetics databases for agriculture"
   citation: "Lisa Harper Jacqueline Campbell Ethalinda K S Cannon Sook Jung Monica Poelchau Ramona Walls, et. al. Database, Volume 2018, 1 January 2018, bay088"
   url: "https://academic.oup.com/database/article/doi/10.1093/database/bay088/5096675"
 - title: "Gene-based SNP discovery in tepary bean (Phaseolus acutifolius) and common bean (P. vulgaris) for diversity analysis and comparative mapping"
   citation: "Neha Gujaria-Verma, Larissa Ramsay, Andrew G. Sharpe, Lacey-Anne Sanderson, Daniel G. Debouck, Bunyamin Tar’an and Kirstin E. Bett. BMC Genomics (2016) 17:239."
   url : "https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-2499-3"
 - title: "Gene-based SNP discovery and genetic mapping in pea"
   citation: "Anoop Sindhu, Larissa Ramsay, Lacey-Anne Sanderson, Robert Stonehouse, Rong Li, Janet Condie, Arun S. K. Shunmugam, Yong Liu, Ambuj B. Jha, Marwan Diapari, Judith Burstin, Gregoire Aubert, Bunyamin Tar’an, Kirstin E. Bett, Thomas D. Warkentin, Andrew G. Sharpe. Theor Appl Genet (2014) 127: 2225."
   url: "https://link.springer.com/article/10.1007/s00122-014-2375-y"
 - title: "Tripal v1.1: a standards-based toolkit for construction of online genetic and genomic databases"
   citation: "Lacey-Anne Sanderson, Stephen P. Ficklin, Chun-Huai Cheng, Sook Jung, Frank A. Feltus, Kirstin E. Bett and Dorrie Main. Oxford Database (2013) bat075"
   url: "https://academic.oup.com/database/article-abstract/doi/10.1093/database/bat075/2871250"
 - title: "Ancient orphan crop joins modern era: gene-based SNP discovery and mapping in lentil"
   citation: "Andrew G Sharpe, Larissa Ramsay, Lacey-Anne Sanderson, Michael J Fedoruk, Wayne E Clarke, Rong Li, Sateesh Kagale, Perumal Vijayan, Albert Vandenberg and Kirstin E Bett. BMC Genomics (2013) 14:192."
   url: "https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-14-192"
 - title: "The Chado Natural Diversity module: a new generic database schema for large-scale phenotyping and genotyping data"
   citation: "Sook Jung, Naama Menda, Seth Redmond, Robert M. Buels, Maren Friesen, Yuri Bendana, Lacey-Anne Sanderson, Hilmar Lapp, Taein Lee, Bob MacCallum, Kirstin E. Bett, Scott Cain, Dave Clements, Lukas A. Mueller and Dorrie Main. Oxford Database (2011) bar051"
   url: "https://academic.oup.com/database/article/doi/10.1093/database/bar051/469438/The-Chado-Natural-Diversity-module-a-new-generic?keytype=ref&ijkey=PMfz4WaoILO7bZJ"
 - title: "Tripal: a construction toolkit for online genome databases"
   citation: "Stephen P. Ficklin, Lacey-Anne Sanderson, Chun-Huai Cheng, Margaret E. Staton, Taein Lee, Il-Hyung Cho, Sook Jung, Kirstin E. Bett and Doreen Main. Oxford Database (2011) bar044"
   url: "https://academic.oup.com/database/article/doi/10.1093/database/bar044/468186"

# An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
#   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I #have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in #addition to others.  In my current role Groovy is the primary language used - and I am #familiar with many of the languages features and quirks (including writing <a #target='_blank' #href="https://dzone.com/articles/functional-programming-groovy">Functional Programming #style groovy</a>). <br/><br/>